version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  rails:
    build: .
    command: bash -c "rm ./tmp/pids/server.pid ; rails db:prepare ; rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/banana
      - node_modules:/home/banana/node_modules
      - packs:/home/banana/public/packs
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
      - webpack
  webpack:
    build: .
    command: bash -c "yarn install ; bin/webpack-dev-server"
    command: bin/webpack-dev-server
    volumes:
      - .:/home/banana
      - node_modules:/home/banana/node_modules
      - packs:/home/banana/public/packs
    ports:
      - "3035:3035"
    expose:
      - "3035"
volumes:
  database_data:
  node_modules:
  packs:
